repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 0.2.1
  hooks:
    - id: sync_with_poetry
